version: '3'
services:
  postgres:
    container_name: 'CultureMap_DB'
    image: postgres:13.13-alpine
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-culturemap}' # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-culturemap}' # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: '${POSTGRES_DB:-culturemap}' # The PostgreSQL default database (automatically created at first launch)
    networks:
      - culturemap
    healthcheck:
      test: [ "CMD", "psql", "-U", "culturemap", "-c", "SELECT 1;" ]
      interval: 1m
      timeout: 10s
      retries: 5

  mailhog:
    container_name: 'CultureMap_MailPit'
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - culturemap

networks:
  culturemap:
    driver: bridge
volumes:
  cmpostgres:
    driver: local
