import React from 'react'
import { Alert } from '@windmill/react-ui'

import { useAuthentication } from '../../hooks'

const DashBoard = () => {
  const [apiUser] = useAuthentication();
  return (
    <>
      <div className={`primary no-secondary is404`}>
        <Alert type="warning">Lorem ipsum dolor sit {apiUser?.id}</Alert>

        <h2>Page Dashboard</h2>
        <p>
          HERE SHOULD an alert be shown if the user has not cofirmed her email... 

        </p>

        <p>
          
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a sodales nulla, sed semper nisi. Cras lobortis volutpat nunc. Proin tincidunt enim in felis aliquet, a ultricies purus bibendum. Quisque in ultrices lectus. Nulla at urna diam. Proin sodales lobortis libero eu facilisis. In sem urna, aliquam vel consectetur sit amet, pulvinar sit amet lectus. Quisque molestie dapibus libero non pellentesque. Vivamus quam arcu, dictum quis hendrerit eget, lobortis eu felis. Nulla felis velit, ornare ac porttitor ut, rhoncus eu ipsum. Donec auctor efficitur est vel congue. Nunc at nunc quis massa facilisis fermentum. Vivamus fringilla nunc vitae justo consectetur, aliquam gravida nisl mollis.</p>
      </div>      
    </>
  )
}
export default DashBoard