# The name given to the PostgreSQL service (lowercase alphanumeric only).
dbpostgres:
    # The type of your service (postgresql), which uses the format
    # 'type:version'. Be sure to consult the PostgreSQL documentation
    # (https://docs.platform.sh/configuration/services/postgresql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: postgresql:13
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 512

# The name given to the Network Storage service (lowercase alphanumeric only).
files:
    # The type of your service (network-storage), which uses the format
    # 'type:version'. Be sure to consult the Network Storage documentation
    # (https://docs.platform.sh/configuration/services/network-storage.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: network-storage:1.0
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 2560

