type ImportHeaders = Record<string, Record<string, string>>;
type ImportRequiredHeaders = Record<string, string[]>;

export const importRequiredHeaders: ImportRequiredHeaders = {
  title: ["title-de", "title-en"],
  description: ["description-de", "description-en"],
  "tax-type-1": ["tax-type-1"],
  street1: ["street1"],
  houseNumber: ["houseNumber"],
  postCode: ["postCode"],
  city: ["city"],
};

export const importHeaders: ImportHeaders = {
  "title-de": { en: "Title (DE)", de: "Name der Einrichtung (DE)" },
  "title-en": { en: "Title (EN)", de: "Name der Einrichtung (EN)" },
  agency: { en: "Name of Agency", de: "Name des Trägers" },
  "tax-agency-type-1": { en: "Type of Agency (1)", de: "Trägerart (1)" },
  "tax-agency-type-2": { en: "Type of Agency (2)", de: "Trägerart (2)" },
  "tax-type-1": { en: "Type (primary)", de: "Einrichtungsart (primär)" },
  "tax-type-2": { en: "Type (2)", de: "Einrichtungsart (2)" },
  "tax-type-3": { en: "Type (3)", de: "Einrichtungsart (3)" },
  "tax-type-4": { en: "Type (4)", de: "Einrichtungsart (4)" },
  "tax-type-5": { en: "Type (5)", de: "Einrichtungsart (5)" },
  "tax-audience-1": { en: "Audience (1)", de: "Zielgruppe (1)" },
  "tax-audience-2": { en: "Audience (2)", de: "Zielgruppe (2)" },
  "tax-audience-3": { en: "Audience (3)", de: "Zielgruppe (3)" },
  "tax-audience-4": { en: "Audience (4)", de: "Zielgruppe (4)" },
  co: { en: "C/O", de: "C/O" },
  street1: { en: "Street (1)", de: "Straße (1)" },
  street2: { en: "Street (2)", de: "Straße (2)" },
  houseNumber: { en: "House number", de: "Hausnummer" },
  postCode: { en: "Post code", de: "PLZ" },
  city: { en: "City", de: "Ort" },
  phone1: { en: "Telefone number (1)", de: "Telefonnummer (1)" },
  phone2: { en: "Telefone number (2)", de: "Telefonnummer (2)" },
  email1: { en: "E-Mail (1)", de: "E-Mailadresse (1)" },
  email2: { en: "E-Mail (2)", de: "E-Mailadresse (2)" },
  "description-de": { en: "Description (DE)", de: "Kurzbeschreibung (DE)" },
  "description-en": { en: "Description (EN)", de: "Kurzbeschreibung (EN)" },
  "offers-de": { en: "Offers (DE)", de: "Angebotsbeschreibung (DE)" },
  "offers-en": { en: "Offers (EN)", de: "Angebotsbeschreibung (EN)" },
  "accessibility-de": {
    en: "Accessibility Info (DE)",
    de: "Barrierefreiheit (DE)",
  },
  "accessibility-en": {
    en: "Accessibility Info (EN)",
    de: "Barrierefreiheit (EN)",
  },
  website: { en: "Website", de: "Webseite" },
  facebook: { en: "Facebook", de: "Facebook" },
  instagram: { en: "Instagram", de: "Instagram" },
  twitter: { en: "Twitter", de: "Twitter" },
  youtube: { en: "Youtube", de: "Youtube" },
  eventLocationId: {
    en: "Berlin.de Event Location Nummer",
    de: "Berlin.de Veranstaltungsort Nummer",
  },
};
